export default {
  contributors: [
    "not-matthias <26800596+not-matthias@users.noreply.github.com>",
    "Matthias <26800596+not-matthias@users.noreply.github.com>",
    "SeniorMars <cjh16@rice.edu>",
    "not-matthias <not-matthias@users.noreply.github.com>",
    "Matthias <not-matthias@protonmail.com>",
    "Constantinos Kyriakidis <kyri@kidis.dev>",
    "Mateusz Jabłoński <github.com@mtsz.pl>",
    "Felix Zwettler <f.zwettler@posteo.de>",
    "Torsten Stöter <torsten.stoeter@lin-magdeburg.de>",
    "Maja Bojarska <majabojarska98@gmail.com>",
    "copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>",
    "diathanine <126717281+P-skylos@users.noreply.github.com>",
    "jack-d-long <jacklong257@gmail.com>",
    "Ali Ghaffaari <ali.ghaffaari@uni-bielefeld.de>",
    "Amir Hosseini <19665344+itsamirhn@users.noreply.github.com>",
    "Claude <noreply@anthropic.com>",
    "Dhruv <83733638+dhruv-ahuja@users.noreply.github.com>",
    "Dipesh Kafle <dipesh.kaphle111@gmail.com>",
    "Ehsan Irani <ehsan.irani@intellisense.io>",
    "Kuan-Lun Wang <polyphonicared@gmail.com>",
    "Peter Kos <pkos91@icloud.com>",
    "Rupert Carr <rupert@cloudflare.com>",
    "Sebastian Müller <gsenpo@gmail.com>",
    "mem.wey <10784701+memwey@users.noreply.github.com>",
    "yonzilch <github@yonzilch.com>",
    "Akhyar Amarullah <akhy@chickenzord.com>",
    "André Sterba <andre@sterba.dev>",
    "Christian Fosli <christian.fosli@capgemini.com>",
    "Christian Fosli <christian.fosli@webstep.no>",
    "Dong Hao <dong_hao@vip.qq.com>",
    "Ehsan Irani <ehsan.irani@protonmail.com>",
    "GitHub Actions <github-actions-bot@users.noreply.github.com>",
    "Jake G <106644+Jieiku@users.noreply.github.com>",
    "Josh Kropf <josh@slashdev.ca>",
    "Kuan-Lun <33048725+Kuan-Lun@users.noreply.github.com>",
    "Sho SHIMIZU <sho.shimizu@gmail.com>",
    "Sima Nerush <2002ssn@gmail.com>",
    "Soumendra kumar sahoo <soumendra.s@outlook.com>",
    "Taichi Kushiro <k.taichi0315@gmail.com>",
    "Timothy DeHerrera <tim@nrdxp.dev>",
    "Tristan Bony <git@tristanbony.me>",
    "Yoichi Hirai <i@yoichihirai.com>",
    "akshay <drdragon79@proton.me>",
    "harish-coeff <harish@coefficient.io>",
    "nune <145225213+gigirassy@users.noreply.github.com>",
    "vac <dot.fun@proton.me>",
    "yfaming <yfaming@gmail.com>",
    "yonzilch <141223334+yonzilch@users.noreply.github.com>"
  ],
  coauthors: [
    "Copilot <175728472+Copilot@users.noreply.github.com>",
    "not-matthias <26800596+not-matthias@users.noreply.github.com>"
  ]
};
